# Generated by Django 3.1.3 on 2020-12-15 17:16

from django.db import migrations, models
import django.db.models.deletion
import orders.models.order
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201215_2045'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='username',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('1', 'Order is begin registered'), ('2', 'Delivered to the sales unit'), ('3', 'Loading'), ('4', 'Sending'), ('5', 'Cleared')], default='1', max_length=1, verbose_name='Order status'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='off',
            field=models.PositiveIntegerField(verbose_name='Off'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=orders.models.order.set_order_number, max_length=100, verbose_name='Order number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.PositiveIntegerField(verbose_name='Total cost'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='off',
            field=models.PositiveIntegerField(verbose_name='Off'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='products'),
        ),
    ]
